events {}

http {
  server {
    listen 80;
    server_name localhost www.localhost; # Change to your domain name

    return 301 https://$host$request_uri;
  }

  server {
    listen 443 ssl;
    server_name localhost www.localhost; # Change to your domain name

    ssl_certificate     /etc/nginx/certs/fullchain.pem;
    ssl_certificate_key /etc/nginx/certs/privkey.pem;

    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;

    location / {
       proxy_pass http://streamlit:8501;
       proxy_http_version 1.1;

       proxy_set_header Upgrade $http_upgrade;
       proxy_set_header Connection "upgrade";

       proxy_set_header Host $host;
       proxy_set_header X-Forwarded-Proto $scheme;
       proxy_set_header X-Forwarded-Host $host;
       proxy_set_header X-Forwarded-Port 443;

       proxy_buffering off;
    }
  }
}